name: Build

on: [push]

jobs:
  build_wheels_macos:
    name: Build wheels on macos-11
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      #- name: Setup Rust dependencies
      #  uses: ATiltedTree/setup-rust@v1
      #  with:
      #    rust-version: 1.65.0
      - name: Test
        run: cargo test

      - name: Build wheels - py38
        run: |
            source ~/miniconda3/etc/profile.d/conda.sh
            conda init zsh
            cd nlpo3-python
            conda activate python38
            python -V
            python -m pip install maturin
            python -m pip list
            python -m maturin build
            conda deactivate
            cd ..
        shell: zsh {0}
      - name: Build wheels - py39
        run: |
            source ~/miniconda3/etc/profile.d/conda.sh
            conda init zsh
            cd nlpo3-python
            conda activate python39
            python -V
            python -m pip install maturin
            python -m pip list
            python -m maturin build
            conda deactivate
            cd ..
        shell: zsh {0}
      - name: Build wheels - py310
        run: |
            source ~/miniconda3/etc/profile.d/conda.sh
            conda init zsh
            cd nlpo3-python
            conda activate python310
            python -V
            python -m pip install maturin
            python -m pip list
            python -m maturin build
            conda deactivate
            cd ..
        shell: zsh {0}
      - uses: actions/upload-artifact@v3
        with:
          path: ./nlpo3-python/target/wheels/*.whl
