name: Test main lib (nlpo3 crate)
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        bitness: [64]  # 32, 64
        include:
          - os: windows-latest
            bitness: 32

    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Setup Rust toolchain - non-win32
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
        if: ${{ !startsWith(matrix.os, 'windows') || matrix.bitness != '32' }}

      - name: Setup Rust toolchain - win32
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: stable
          target: i686-pc-windows-msvc
        if: startsWith(matrix.os, 'windows') && matrix.bitness == '32'

      - name: Setup Rust dependencies
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Cache Rust files
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Install dependencies on ubuntu
#      - name: Install build dependencies
#        run: sudo apt-get install -y libxml2-dev libxslt-dev
#        if: matrix.os == 'ubuntu-latest'

      - name: Build Rust crate
        run: cargo build --release

      - name: Test
        run: cargo test
