# Build wheels for many platforms
# see: https://github.com/pypa/cibuildwheel

name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Setup build enc
        run: |
          python -m pip install --upgrade wheel setuptools setuptools-rust

      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        with:
          output-dir: wheelhouse
        env:
          CIBW_BUILD: ${{ matrix.target }}
          CIBW_PLATFORM: ${{ matrix.platform || matrix.os }}
          CIBW_BEFORE_BUILD_LINUX: >
            pip install -U setuptools-rust &&
            curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=nightly --profile=minimal -y
          CIBW_BEFORE_BUILD_WINDOWS: 'rustup default nightly'
        CIBW_ENVIRONMENT: 'PATH="$HOME/.cargo/bin:$PATH"'
        CIBW_ENVIRONMENT_WINDOWS: 'PATH="$HOME\.cargo\bin:$PATH"'

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
